image: gitpod/workspace-mongodb

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - octref.vetur@0.28.0:bW1RGNnmWYQO43JdJgK34w==
